### ISSUE TITLE
Ubuntu dependencies should include ruby

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry-community/bosh-init-bosh#2]
The instructions in the README:

```
sudo apt-get install -y build-essential zlibc zlib1g-dev \
  openssl libxslt-dev libxml2-dev libssl-dev \
  libreadline6 libreadline6-dev libyaml-dev libsqlite3-dev sqlite3
```

are insufficient; ruby must also be installed.

**Comment by drnic** [comment]
Rob this shouldn't be the case - can you show me the error so I can have a look and/or escalate to bosh team?

The AWS CPI release includes its own Ruby which will be compiled on first deploy.

**Comment by drnic** [comment]
Just saw the other issue - I forgot to go through upgrading each tutorial project to new CPI v7. Want to try that with this project and confirm it works?
